title: Yujie Tao
url: "https://yujietao.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This guy designed the page."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 # - name: "CV"
 #   link: "Yujie_Tao_CV.pdf"
 - name: "Blog"
   link: "blog"
